services:
  mysql:
    image: mysql:8.0
    container_name: floe-db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
     - db-data:/var/lib/mysql

  backend:
    build:
      context: ./Floe-Backend/floe
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
     - .env  # 부모의 .env 파일 사용
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:7.4
    container_name: floe-redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: ["redis-server", "--save", "''", "--appendonly", "no"] # db 기능 비활성화

volumes:
  db-data:
